{{- $root := . -}}
{{- $driverMonitoring := toJson (fromYaml (tpl (.Files.Get "monitoring/metrics.yaml") .)).driver_instances }}
{{- $executorMonitoring := toJson (fromYaml (tpl (.Files.Get "monitoring/metrics.yaml") .)).executor_instances }}
{{- $driverTags := toJson (fromYaml (tpl (.Files.Get "monitoring/tags.yaml") .)).driver }}
{{- $executorTags := toJson (fromYaml (tpl (.Files.Get "monitoring/tags.yaml") .)).executor }}
{{ range $k, $app := .Values.apps }}
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: {{ $app.fullnameOverride }}
  labels:
    app.kubernetes.io/name: {{ include "spark.name" $root }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
spec:
  type: {{ $root.Values.sparkApplication.type }}
  mode: {{ $root.Values.sparkApplication.mode }}
  image: "{{ $root.Values.image.repository }}:{{ $root.Values.image.tag }}"
  imagePullPolicy: {{ $root.Values.image.pullPolicy }}
  mainClass: {{ $app.mainClass }}
  {{- with $app.arguments }}
  arguments:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  mainApplicationFile: {{ $root.Values.sparkApplication.mainApplicationFile }}
  sparkVersion: {{ $root.Values.sparkApplication.version }}
  sparkConf:
    {{- toYaml $root.Values.sparkApplication.conf | nindent 4 }}
    {{- with $app.conf }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  restartPolicy:
    type: {{ $root.Values.sparkApplication.restartPolicy.type }}
  {{- with $root.Values.sparkApplication.volumes }}
  volumes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  driver:
    javaOptions: {{ $app.driver.javaOptions }}
    annotations:
      ad.datadoghq.com/spark-kubernetes-driver.tags: '{{ $driverTags }}'
      ad.datadoghq.com/spark-kubernetes-driver.check_names: |
        ["openmetrics"]
      ad.datadoghq.com/spark-kubernetes-driver.init_configs: |
        [{}]
      ad.datadoghq.com/spark-kubernetes-driver.instances: '{{ $driverMonitoring }}'
    env:
    {{- with $root.Values.sparkApplication.commonEnvs }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with $app.envs }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    envSecretKeyRefs:
    {{- with $root.Values.sparkApplication.commonEnvSecretKeyRefs }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with $app.envSecretKeyRefs }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    cores: {{ $app.driver.cores }}
    coreLimit: {{ $app.driver.coreLimit }}
    memory: {{ $app.driver.memory }}
    memoryOverhead: {{ $app.driver.memoryOverhead }}
    labels:
      version: {{ $root.Values.sparkApplication.version }}
    serviceAccount: {{ include "spark.serviceAccountName" $root }}
    {{- with $root.Values.sparkApplication.volumeMounts }}
    volumeMounts:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with $app.tolerations }}
    tolerations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with $app.affinity }}
    affinity:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  executor:
    javaOptions: {{ $app.executor.javaOptions }}
    annotations:
      ad.datadoghq.com/spark-kubernetes-executor.tags: '{{ $executorTags }}'
      ad.datadoghq.com/spark-kubernetes-executor.check_names: |
        ["openmetrics"]
      ad.datadoghq.com/spark-kubernetes-executor.init_configs: |
        [{}]
      ad.datadoghq.com/spark-kubernetes-executor.instances: '{{ $executorMonitoring }}'
    {{- with $app.envs }}
    env:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with $app.envSecretKeyRefs }}
    envSecretKeyRefs:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    cores: {{ $app.executor.cores }}
    coreLimit: {{ $app.executor.coreLimit }}
    memory: {{ $app.executor.memory }}
    memoryOverhead: {{ $app.executor.memoryOverhead }}
    labels:
      version: {{ $root.Values.sparkApplication.version }}
    serviceAccount: {{ include "spark.serviceAccountName" $root }}
    {{- with $root.Values.sparkApplication.volumeMounts }}
    volumeMounts:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with $app.tolerations }}
    tolerations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with $app.affinity }}
    affinity:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  monitoring:
    exposeDriverMetrics: {{ $root.Values.sparkApplication.monitoring.exposeDriverMetrics }}
    exposeExecutorMetrics: {{ $root.Values.sparkApplication.monitoring.exposeExecutorMetrics }}
    prometheus:
      jmxExporterJar: {{ $root.Values.sparkApplication.monitoring.prometheus.jmxExporterJar }}
      port: {{ $root.Values.sparkApplication.monitoring.prometheus.port }}
  dynamicAllocation:
    enabled: {{ $app.dynamicAllocation.enabled }}
    initialExecutors: {{ $app.dynamicAllocation.initialExecutors }}
    minExecutors: {{ $app.dynamicAllocation.minExecutors }}
    maxExecutors: {{ $app.dynamicAllocation.maxExecutors }}
{{ end }}